### ISSUE TITLE
GitHub Readme

### ISSUE THREAD

**Issue by AndyMagwayer** [PurpleMonkey729/HorseRaceGame-dev#13]
Hey bro you can do deploying of your projects on the REadme, I mean from my view you should somehow decorate your REadme files , do deploying in netlufy and dont forget to pin them , but regarding this project it is very taugh you did great work , do your best ))

**Comment by AndyMagwayer** [comment]
i mean , do decorated REdme files with images and deploying in it)

**Comment by AndyMagwayer** [comment]
aaa got it bro no problem, and i want to ask u about the multiply project i mean we can do some project together )

**Comment by PurpleMonkey729** [comment]
Thanks, bro. So what project do you think?
